import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./component/theme/ThemeProvider";
import { Header } from "./component/ui/header";
import { tmdbService } from "./_lib/service/tmdbService";

export const montserrat = Montserrat({
  subsets: ['latin'], // Specify required subsets
  variable: '--font-montserrat', // Define a CSS variable for easier use
  weight: ['400', '500', '700'], // Specify desired weights
});

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const genres = await tmdbService.getAllGenre()

  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased `}

      >
        <ThemeProvider defaultTheme="dark">
          <div className="relative">
            <Header genres={genres} />
            <div>
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
